services:

  mongo:
    image: mongo:latest
    container_name: chat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - chat-network

  server:
    build: ./server
    container_name: chat-server
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/chatapp
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - chat-network

  client:
    build: ./client
    container_name: chat-client
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server
    networks:
      - chat-network

volumes:
  mongo_data:

networks:
  chat-network:
    driver: bridge