FROM node:20-alpine

WORKDIR /app

COPY package.json ./

RUN npm config set fetch-timeout 120000 && npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retry-maxtimeout 120000 && npm install --legacy-peer-deps

COPY . .

EXPOSE 5000

CMD ["node", "server.js"]